# IN THE NAME OF GOD

### Introduction to Numpy and Pandas

In [7]:
# like string concatenation
a = [1, 2, 3]
b = [4, 5, 6]
c = a + b
print(type(c))
print(c)
print('right way: ')
c = []
for i in range(len(a)):
    c.append(a[i] + b[i])
print(c)

<class 'list'>
[1, 2, 3, 4, 5, 6]
right way: 
[5, 7, 9]


In [8]:
import numpy as np

In [30]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
add = a + b
sub = a - b
mul = a * b
dev = a / b
print(add)
print(sub)
print(mul)
print(dev)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [16]:
# ضرب نقطه ای
dot = np.dot(a, b)
print(dot)

32


تفاوت بین ضرب نقطه ای و ضرب ماتریسی

ماتریس صفر

In [20]:
z = np.zeros((2,3))
print(z)
print(z.size)

[[0. 0. 0.]
 [0. 0. 0.]]
6


ماتریس یکه
عدد به صورت 
1.
یعنی دقیقا یک و اعشار ندارد

In [21]:
o = np.ones((3, 3))
print(o)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


دسترسی به یک آرایه خاص در ماتریس

In [25]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x.shape)

(2, 3)


In [26]:
print(x.size)

6


In [27]:
x1 = x.reshape(3, 2)
print(x1)

[[1 2]
 [3 4]
 [5 6]]


In [32]:
x2 = x.reshape(6, 1)
print(x2)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


میانگین - استاندارد دبییشن - ...

در مثال زیر آرایه ای که
standard deviation
کمتری داشته باشد یعنی داده ها نزدیک مرکز که میانگی است هستند، بهتر است.
کلا اگر 
standard deviation
کم باشد خوبه

در مثال زیر 
mean = 3
std = 1.41
====> 1.5 , 4.5
اعداد 1.5 و 4.5 نشاندهنده این هستند که ما در این فاصله بیشترین تجمع داده را داریم.

In [43]:
'''
NOTE 1:
    To calculate mean: np.mean(arr1)

NOTE 2:
    To calculate standard deviation: np.std(arr1)
'''

data = np.array(([1, 2, 3, 4, 5]))
# mean
m = np.mean(data)
# standard deviation
std = np.std(data)

data1 = np.array([-1, -2, 3, 6, 9])
# mean
m1 = np.mean(data1)
# standard deviation
std1 = np.std(data1)

print(f"Data | mean: {m} , std: {std}")
print(f"Data1 | mean1: {m1} , std1: {std1}")

Data | mean: 3.0 , std: 1.4142135623730951
Data1 | mean1: 3.0 , std1: 4.147288270665544


In [46]:
data = np.array(([1, 2, 3, 4, 5]))

sin_data = np.sin(data)
cos_data = np.cos(data)
print(sin_data, '\n', cos_data)

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427] 
 [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]


ضرب ماتریس ها

In [50]:
mat_a = np.array(([1, 2], [4, 5]))
mat_b = np.array(([7, 8], [10, 11]))

mat_p = np.matmul(mat_a, mat_b)
print(mat_p)

[[27 30]
 [78 87]]


In [51]:
# a real word exampl in matmul
a = np.array(([2, 1], [1, 4]))
b = np.array(([1, 2, 0], [0, 1, 2]))
c = np.matmul(a, b)
print(c)

[[2 5 2]
 [1 6 8]]


محاسبه دترمینال یک ماتریس

In [53]:
a = np.array(([2, 1], [1, 4]))
det_a = np.linalg.det(a)
print(det_a)

7.000000000000001


معکوس یک ماتریس

In [62]:
a = np.array(([2, 1], [1, 4]))
print(f"mat a:\n{a}\n")

inverse = np.linalg.inv(a)
print('inverse')
print(inverse)

print('\ncalculating a * inverse: ')
result = np.matmul(a, inverse)
print(result)

mat a:
[[2 1]
 [1 4]]

inverse
[[ 0.57142857 -0.14285714]
 [-0.14285714  0.28571429]]

calculating a * inverse: 
[[1. 0.]
 [0. 1.]]


ایجاد ماتریس رندوم با تعداد درایه های دلخواه

In [84]:
# np.random.rand
rand = np.random.rand(3, 2)
print(rand)

rand *= 5
print(rand)

[[0.67773706 0.51148495]
 [0.8990179  0.01253355]
 [0.60761243 0.52888481]]
[[3.38868532 2.55742476]
 [4.49508952 0.06266776]
 [3.03806215 2.64442406]]


ایجاد ماتریس رندوم که درایه های آن نرمال شده اند. این ماتریس توزیع نرمال نام دارد. جمع همه درایه ها با هم صفر است.
میانگین ماتریس های نرمال شده صفر است

In [87]:
# np.rand.randn
rand_normal = np.random.randn(3, 2)
print(rand_normal)

mean = np.mean(rand_normal)
print(f'mean: {mean}')

[[ 0.11191462 -0.33436603]
 [ 1.11370043  0.05991373]
 [ 0.04586364 -1.34897168]]
mean: -0.0586575481669955


شروع کتابخانه

pandas

In [91]:
import pandas as pd

In [94]:
data = {
        'Name': ['Abbas', 'Akbar', "Ahmad"],
        'Age': [25, 29, 81],
        'City': ['Tehran', 'Boshehr', 'Abadan']
        }
df = pd.DataFrame(data)
print(df)

    Name  Age     City
0  Abbas   25   Tehran
1  Akbar   29  Boshehr
2  Ahmad   81   Abadan


In [96]:
# print some lines and specificly, the head of table
print(df.head)

<bound method NDFrame.head of     Name  Age     City
0  Abbas   25   Tehran
1  Akbar   29  Boshehr
2  Ahmad   81   Abadan>


In [97]:
print(df.info)

<bound method DataFrame.info of     Name  Age     City
0  Abbas   25   Tehran
1  Akbar   29  Boshehr
2  Ahmad   81   Abadan>


In [99]:

print(df.describe())

             Age
count   3.000000
mean   45.000000
std    31.240999
min    25.000000
25%    27.000000
50%    29.000000
75%    55.000000
max    81.000000


In [102]:
ages = df['Age']
print(ages)

0    25
1    29
2    81
Name: Age, dtype: int64


In [105]:
selected = df[['Name', 'City']]
print(selected)

    Name     City
0  Abbas   Tehran
1  Akbar  Boshehr
2  Ahmad   Abadan


نمایش یک سطر

In [108]:
row1 = df.loc[1]
print(row1)

Name      Akbar
Age          29
City    Boshehr
Name: 1, dtype: object
